# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f03f31e282b9b6a0ae5fb4a17bae999f448e2601ff7e4cb322e5e9c91c219f2035bbd6fa48553e085f7cbc955e5c069d652318fd8d9ce2095059e00df2318a59

test:
  secret_key_base: ba890f05c8c086acadb1b4505d905b4839bffefbebc55dc1627f53a0bf5506267a1972f992af0b0d2e12f3709de5a4d7e36594aefb665f3b32882835e09ad993

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
